name: mackup
version: 0.8.16
summary: Keep your application settings in sync
description: |
  Back ups your application settings in a safe directory (e.g. Dropbox).
  Syncs your application settings among all your workstations.
  Restores your configuration on any fresh install in one command line.

grade: devel
confinement: classic

apps:
  mackup:
    command: bin/mackup

parts:
  mackup:
    plugin: python
    python-version: python2
    source: https://github.com/lra/mackup.git
    source-tag: 0.8.16
